// lib/firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDA3wMl5oG8WSYlW-c2u20YdguVuTGKgE',
    appId: '1:1037275828456:web:223f739045422d7063795d',
    messagingSenderId: '1037275828456',
    projectId: 'jogo-da-velha-ia-app',
    authDomain: 'jogo-da-velha-ia-app.firebaseapp.com',
    storageBucket: 'jogo-da-velha-ia-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjBWsWDz1YVQulPWC1rBrKJf_bMDTWUT4',
    appId: '1:1037275828456:android:01846948d29806ac63795d',
    messagingSenderId: '1037275828456',
    projectId: 'jogo-da-velha-ia-app',
    storageBucket: 'jogo-da-velha-ia-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJXOpo6JMFJBIBx00DQquhWu4n3v-scFQ',
    appId: '1:1037275828456:ios:df7373cb0b438aa863795d',
    messagingSenderId: '1037275828456',
    projectId: 'jogo-da-velha-ia-app',
    storageBucket: 'jogo-da-velha-ia-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJXOpo6JMFJBIBx00DQquhWu4n3v-scFQ',
    appId: '1:1037275828456:ios:df7373cb0b438aa863795d',
    messagingSenderId: '1037275828456',
    projectId: 'jogo-da-velha-ia-app',
    storageBucket: 'jogo-da-velha-ia-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDA3wMl5oG8WSYlW-c2u20YdguVuTGKgE',
    appId: '1:1037275828456:web:0971381a2fa6e9bb63795d',
    messagingSenderId: '1037275828456',
    projectId: 'jogo-da-velha-ia-app',
    authDomain: 'jogo-da-velha-ia-app.firebaseapp.com',
    storageBucket: 'jogo-da-velha-ia-app.firebasestorage.app',
  );
}